### ISSUE TITLE
Kanban Board Setup

### ISSUE THREAD

**Issue by jmoseka** [ichala/space-travelers-hub#21]
Hello, 
In this project, we are a team of two students @ichala and I. Please, find the Kanban Board board project [here](https://github.com/ichala/space-travelers-hub/projects/1)

NB: We followed all steps to set up our Kanban Board. However, most of the issues got copied but not all of them. They are total of 27 issues on the [template](https://github.com/microverseinc/curriculum-react-redux/projects/1
) but only 20 of them got copied in our project. 
We also removed the project of the 3rd team member which has become 13 total issues.

**Comment by Deepakdanger** [comment]
Hi @TEAM, 

Good job so far! 👏
There are some issues that you still need to work on to go to the next project but you are almost there!

## To Highlight :100: 

## Required Changes ♻️
- [x] you have missed some group task and some task , Kindly add these
- [[1pt] Create app and install basic dependencies - Setup (group task)](https://github.com/microverseinc/curriculum-react-redux/issues/47)
- [[1pt] Create website header with empty nav - Setup (group task)](https://github.com/microverseinc/curriculum-react-redux/issues/51)
- [[1pt] Create empty My profile - Setup (group task)](https://github.com/microverseinc/curriculum-react-redux/issues/52)
- [[1pt] Create basic structure for Rockets - Setup](https://github.com/microverseinc/curriculum-react-redux/issues/50)

- [x] All cards are assigned to team members. You should see a circle with the user's avatar on each card. See the example below:
![image](https://user-images.githubusercontent.com/26767383/173320132-1bde7acc-f83b-4b0d-ad47-f77609d7dda4.png)
- The card point assigned to student should be (difference <= 5 points )





## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by ichala** [comment]
Updated all required changes 👍

**Comment by Munsa1** [comment]
Hi Team, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights
:heavy_check_mark: Descriptive Readme
:heavy_check_mark: Passing Linters
:heavy_check_mark: Correct Gitflow

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
